### ISSUE TITLE
Twitch Integration

### ISSUE THREAD

**Issue by MaroStClair** [pollend/ParkitectTwitchIntegration#1]
Hello! Wonderful mod, been waiting for this to happen for so long. Finally!
Just a question. On the Parkitect Nexus it doesn't actually say what, and in what format, I should put it in:
- Stream User Name
- Stream Channel Name
- Auth code

The link to the auth code works perfectly and I think the code works, I'm just having problems figuring out how I should write in my details in the other two boxes. I wrote mine like this:

Twitch User Name: MaroStClair
Twitch Channel Name: http://www,twitch,tv/MaroStClair
Twitch Auth Token: ********_the auth token I found in the link**_******

Is this correct?

**Comment by pollend** [comment]
the channel name should just be MaroStClair

**Comment by MaroStClair** [comment]
I've tried that and it didn't work:
User Name: MaroStClair
Channel Name: MaroStClair
Twitch Auth Token: *****_the auth token I found in the link**_***

**Comment by pollend** [comment]
Just tested it on my own machine and it seems to work correctly. Did you try copy the token into the Config.json located in pnmods/pollend@ParkitectTwitchIntegration/Config.json.

**Comment by MaroStClair** [comment]
Hello! Me again!

I jumped back on the game and wanted to check out this mod again to see if I could get it working. But now, I've run into other problems. 
When installing the mod, I get 6 compile errors, and Nexus tells me to check mod.log. And here it is:


[17-04-22 01:20:16] Info: Compiling Twitch Integration to bin/build-170422012016891.dll...
[17-04-22 01:20:16] Info: Compiling from `TwitchIntegration.csproj`.
[17-04-22 01:20:16] Info: Resolved assembly reference `System` to `System.dll`
[17-04-22 01:20:16] Info: Resolved assembly reference `Assembly-CSharp` to `D:\SteamLibrary\SteamApps\common\Parkitect\Parkitect_Data\Managed\Assembly-CSharp.dll`
[17-04-22 01:20:16] Info: Resolved assembly reference `UnityEngine` to `D:\SteamLibrary\SteamApps\common\Parkitect\Parkitect_Data\Managed\UnityEngine.dll`
[17-04-22 01:20:16] Info: Resolved assembly reference `UnityEngine.UI` to `D:\SteamLibrary\SteamApps\common\Parkitect\Parkitect_Data\Managed\UnityEngine.UI.dll`
[17-04-22 01:20:16] Info: IGNORING assembly reference `build-160719205732854`
[17-04-22 01:20:16] Info: Source files: AssemblyInfo.cs, Configruation.cs, Main.cs, Settings.cs, TwitchIntegration.cs, TwitchGuestAssocCollection.cs, GuestTwitchThough.cs from `C:\Users\Evelina MP\Documents\Parkitect\pnmods\pollend@ParkitectTwitchIntegration\.`.
[17-04-22 01:20:16] Info: Compile using compiler version v3.5.
[17-04-22 01:20:16] Error: CS0019: 114:17: Det går inte att använda operatorn += i operander av typen System.EventHandler och lambda-uttryck in c:\Users\Evelina MP\Documents\Parkitect\pnmods\pollend@ParkitectTwitchIntegration\TwitchIntegration.cs
[17-04-22 01:20:16] Error: CS1501: 115:21: Ingen överlagring för metoden addNotification tar 3 argument in c:\Users\Evelina MP\Documents\Parkitect\pnmods\pollend@ParkitectTwitchIntegration\TwitchIntegration.cs
[17-04-22 01:20:16] Error: CS0019: 144:17: Det går inte att använda operatorn += i operander av typen System.EventHandler och lambda-uttryck in c:\Users\Evelina MP\Documents\Parkitect\pnmods\pollend@ParkitectTwitchIntegration\TwitchIntegration.cs
[17-04-22 01:20:16] Error: CS1501: 174:25: Ingen överlagring för metoden addNotification tar 3 argument in c:\Users\Evelina MP\Documents\Parkitect\pnmods\pollend@ParkitectTwitchIntegration\TwitchIntegration.cs
[17-04-22 01:20:16] Error: CS0019: 234:17: Det går inte att använda operatorn += i operander av typen System.EventHandler och lambda-uttryck in c:\Users\Evelina MP\Documents\Parkitect\pnmods\pollend@ParkitectTwitchIntegration\TwitchIntegration.cs
[17-04-22 01:20:16] Error: CS1501: 235:21: Ingen överlagring för metoden addNotification tar 3 argument in c:\Users\Evelina MP\Documents\Parkitect\pnmods\pollend@ParkitectTwitchIntegration\TwitchIntegration.cs


I don't know why the log came out in Swedish but the first error cs0019 says: "Can't use operator += in operations of the type System.Event...."
Second error CS1501 says: "No overlay for method addNotification takes 3 argument in c:...."
And those two are just repeated again.

I hope they are of any help, because I have no clue how to fix this.
